baseURL = "https://www.sorvestlig.com/"
languageCode = "en-us"
title = "sørvestlig"

theme = "PaperMod"

[pagination]
pagerSize = 5

[params]
defaultTheme = "auto"
ShowReadingTime = true
ShowCodeCopyButtons = true

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 10

[[menu.main]]
identifier = "team"
name = "team"
url = "/team/"
weight = 20

[[menu.main]]
identifier = "careers"
name = "careers"
url = "/careers/"
weight = 30

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true