baseURL = "https://www.sorvestlig.com/"
languageCode = "en-us"
title = "sørvestlig"

theme = "PaperMod"

[pagination]
pagerSize = 5

[params]
defaultTheme = "auto"
ShowReadingTime = true
ShowCodeCopyButtons = true

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 10

[[menu.main]]
identifier = "team"
name = "Team"
url = "/team/"
weight = 20

[[menu.main]]
identifier = "careers"
name = "Careers"
url = "/careers/"
weight = 30

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  disableHugoGeneratorInject = true

  # This forces the homepage list to show projects instead of careers
  mainSections = ["projects"]
